language: rust
rust:
  - stable
install:
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo clean
  - cargo fmt --all -- --check
  - cargo clippy -- --deny clippy::pedantic
  - cargo test
  - cargo run
