[package]
name = "paxos"
version = "1.0.0"
authors = ["Stephan Boyer <stephan@stephanboyer.com>"]
edition = "2018"

[dependencies]
bincode = "1"
futures = "0.1"
hyper = "0.12"
serde_yaml = "0.8"
tokio = "0.1"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.clap]
version = "2"
default-features = true
features = ["wrap_help"]
